### ISSUE TITLE
Ray tracing in opposite direction

### ISSUE THREAD

**Issue by dedean16** [mitsuba-renderer/mitsuba2#118]
Hi,

I'd like to perform inverse rendering on a scene of an experimental setup with a CCD camera without any lens, having light rays coming in from all directions for every pixel, rather than a pinhole or thin-lens-camera. Furthermore, the light source will be either a collimated beam or a focused beam, with only one direction (or perhaps a very narrow angle distribution) per position.

Since for most 'normal' scenes this situation is the other way around (pinhole camera + diffuse emitter), most renderers (including mitsuba as far as I understand) actually start the rays from the camera, tracing them back to the light source. However, in a case like the above scene description, I think it would be much more efficient to trace the rays from the light source towards the CCD plane.

Do you think it would be necessary to implement this reverse direction ray tracing to efficiently resolve such a scene? If so, would it be possible to implement this in Mitsuba2 as 'plugins', given its modular nature? If not, how would you recommend to set up such a scene? For instance, mimicking a CCD by having an orthogonal camera looking at a diffuse plane, perhaps?

I would greatly appreciate any help/advice! Thanks for creating Mitsuba :)

Cheers,
Daniël

**Comment by Speierers** [comment]
Hi @dedean16 ,
Indeed in your case it would be more efficient to construct light path starting from the light source and later connect to the camera. 

If you aren't famiar with light tracing and bidirectional path tracing techniques, I would strongly recommend you to start by reading about those 😉 

Your "light tracer" integrator should overwrite not only the `sample()` method but also the `render()` method in order to control how rays are created. In your case, they would be generated using the `sample_ray()` method on the emitters.

You will also have to implement your own sensor plugin, which will probably need to overwrite the `sample()` , (maybe even `pdf()` and `eval()`) method as you want to connect to it.

Good luck with your project!

**Comment by dedean16** [comment]
Thanks for your response! I'll look into the sample, render and sensor methods :)
