### ISSUE TITLE
Prebuilt Windows binaries?

### ISSUE THREAD

**Issue by oscarbg** [mitsuba-renderer/mitsuba2#148]
Hi,

it's much to ask for prebuilt Windows binaries.. I think may be a potential huge user base and also on Windows people may be more lazy to install VS2019 , CUDA SDK and Optix SDK just to use it..

thanks..
EDIT: also Mac binaries wouldn't be bad :-)

**Comment by Speierers** [comment]
Hi @oscarbg,

We are currently working on make the build process easier regarding the CUDA dependency.

However please keep in mind that Mitsuba is an advanced tool for researchers, so we expected users to be able to compile it themselves.

**Comment by Euph0ria** [comment]
Fractal/graphical software Visions of Chaos has an option to support Mitsuba-renderer though it's not made for researchers.  Is this something you frown on because people might use it much more widely, or pompous enough to feel that if you don't know how to compile source code, you don't deserve to use the software?

**Comment by Speierers** [comment]
With the upcoming version of Mitsuba, you will be able to use the framework without having to compile it yourself. Just need to wait for a little longer.
