### ISSUE TITLE
Adding a Disney BSDF Plugin

### ISSUE THREAD

**Issue by bathal1** [mitsuba-renderer/mitsuba2#153]
Adding an implementation of the Disney BSDF in mitsuba 2 would be really nice, as it would allow for more compatibility with scenes that weren't created for mitsuba initially. For instance, it would be nice to be able to export Principled BSDF nodes from Blender.

I'll try to implement this.

**Comment by KoykL** [comment]
I was trying to work on similar things. I have just implemented the diffuse and specular lobe of the Disney bsdf (with NO subsurface scattering, transmission, or anisotropic support) 

Since I am new to rendering, I am not very confident about my implementation. I am still trying to figure out if my implementation is correct or not. 

If it's helpful, I am happy share the code on that part, but I guess I need to first verify the implementation though.

**Comment by jiangwei007** [comment]
Yes,this feature is very important，i'm really looking forward to this enhancement

**Comment by wjakob** [comment]
This feature is available in Mitsuba 3: https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_bsdfs.html#the-principled-bsdf-principled
