### ISSUE TITLE
Store/resume rendering

### ISSUE THREAD

**Issue by gianlucaagresti** [mitsuba-renderer/mitsuba2#197]
Hello,
Is there a tool to store a checkpoint and then resume later a rendering?
Otherwise, is it possible to save intermediate results of a rendering?
Thank you.

Best regards,
Gianluca

**Comment by Speierers** [comment]
Hi @gianlucaagresti ,

No, Mitsuba 2 doesn't provide any "checkpoint" feature, although it is easy to get intermediate results as `Bitmap` objects and later averaging those (e.g. muli-pass rendering).

You can do this without having to re-load the scene. (at least with `independent` sampler).

I will close this as it is not an issue.

Cheers

**Comment by merlinND** [comment]
If that helps, when you can send a `SIGHUP` signal to the `mitsuba` process to write out an image with the current state:

https://github.com/mitsuba-renderer/mitsuba2/blob/695eefed46e9536a65ee61e7fc4f4134c303c682/src/mitsuba/mitsuba.cpp#L112-L121

Otherwise, the simple way that @Speierers  suggested is probably the best one: split your large rendering problem into several smaller ones (e.g. 64k spp -> 64 * 1k spp). Render each "pass" individually with a different sampler seed, and average the results together.

**Comment by gianlucaagresti** [comment]
Ok, I see the point. 
However, is a rendering with K samples statistically identical to the mean of N renderings with K/N samples (and different seed of course)? Are there no other operations to combine the rays?
Thank you for the support.

Best regards,
Gianluca

**Comment by Speierers** [comment]
Those will be statistically identical (you need to use different seed indeed). 

You can also take a look at what's done with the `samples_per_pass` property in the `integrator.cpp` as it splits renders (for gpu modes) in multiple passes if requested.

**Comment by gianlucaagresti** [comment]
Thank you for the answer and the support.

Best regards,
Gianluca
