### ISSUE TITLE
Spectral Absorption

### ISSUE THREAD

**Issue by xHotch** [mitsuba-renderer/mitsuba2#234]
- [❔ other question]

## Description

Hello,

I am currently working on a project where I need to model materials that absorb light differently at different wavelengths. I am only interested in the absorption of the materials, so no scattering is required.

As the Documentation for the Volumetric Integrators is missing, I am unsure how I could achieve this.
Is this something that is already included in Mitsuba2? 

Thanks in advance.

**Comment by dvicini** [comment]
Hi,

Yes, you can do that using the `volpathmis` integrator. The interface to use volumes is very close to Mitsuba 1, but we havent had the cycles yet to document it properly. To see some example scenes, you can have a look at the scenes under `resources/data/tests/scenes/participating_media'.

To create a medium which only absorbs light, you would want to set `sigma_t` to your desired absorption and `albedo` to zero.

In a scene XML, you could create such a medium like this:
```
    <medium id="medium1" type="homogeneous">
        <float name="scale" value="3"/> 
        <rgb name="sigma_t" value="1, 0.2, 1"/>
        <rgb name="albedo" value="0.0, 0.0, 0.0"/>
        <phase type="isotropic" />
    </medium>
    <shape type="obj">
        <string name="filename" value="my_medium_boundary.obj"/>
        <bsdf type="null">
        </bsdf>
        <ref id="medium1" name="interior"/>
    </shape>
```
The `scale` parameter of the medium scales the extinction values, since they are currently required to be between 0 and 1
Delio
