### ISSUE TITLE
[❔ other question] What's the best way to render volume densities?

### ISSUE THREAD

**Issue by seashell123** [mitsuba-renderer/mitsuba2#251]
I am interested in rendering volume densities in Mitsuba. One idea I have so far is to convert my volume densities into depth maps (by computing the expected ray termination depth for each ray for multiple viewpoints), merge across views to create a point cloud of the object surface, then convert from point cloud to mesh, and finally load the mesh into Mitsuba. Is there a better way of doing this?

**Comment by dvicini** [comment]
Hi,

This is currently not really documented, but Mitsuba can render volumes using the `volpath` and `volpathmis` integrators. The interface and the file format for the volume grids is mostly identical to Mitsuba 1 (see the section on volumes in  https://www.mitsuba-renderer.org/releases/current/documentation.pdf ). There is also a small tool to convert OpenVDB densities to the Mitsuba volume format: https://github.com/mitsuba-renderer/mitsuba2-vdb-converter

We will soon add some documentation for the volumes so that these things become a bit more clear. I am closing this issue for now. 

Delio
