### ISSUE TITLE
How to get extrinsic parameters from XML files

### ISSUE THREAD

**Issue by alexzhou907** [mitsuba-renderer/mitsuba2#259]
There doesn't seem to any interface specifically for this. Can anyone provide an example of given 'perspective' tag of target, origin, and up, how to get the extrinsic camera parameters?

**Comment by Speierers** [comment]
Hi @alexzhou907 ,

There is currently to code/interface for this in Mitsuba 2. Although it shouldn't be too hard to reconstruct the intrisic/extrinsic matrices given the camera parameters. See this:
https://link.springer.com/referenceworkentry/10.1007%2F978-0-387-31439-6_152

**Comment by ram-bhaskara** [comment]
Having been worked with Mitsuba for about two years now, I always felt that it is not straightforward to compute camera intrinsic matrix from the XML parameters. This is because
1) Mitsuba specifies FOV in degree (diagonal/axis) -> we need to convert this to fx, fy (pixel units)
1.1) This inturn requires the scaling (mm to px) -> the clue here from Mitsuba documentation is that it uses a 35 mm film equivalent to specify focal length, I used this information to convert to pixel scale and build the intrinsic matrix therefrom.

Focal length, focus distance - there is a lot of optics to understand while/before working with Mitsuba. 

I don't know why this important computer vision application using Mitsuba is not treated aptly in the public domain.  Will try to post my function once I validate it enough.

**Comment by merlinND** [comment]
Hello @ram-bhaskara,

This sounds like a useful feature to have! Feel free to open a PR or Discussion in the [mitsuba3](https://github.com/mitsuba-renderer/mitsuba3) repo if you'd like to share your function.

**Comment by ram-bhaskara** [comment]
Hello, 

If you're using Mitsuba to generate synthetic images for computer vision, here is a way to translate your camera parameters from XML to camera intrinsic matrix (for projection transformation):

If your sensor object represents a pinhole model with field of view and resolution parameters - you need not go into the intricate details of film width like optics knowledge to figure out camera intrinsic matrix. Rather use the image geometry -

```
(% MATLAB CODE %)

vfov = 30; % deg
img_width = 500; % pixels
img_height = 500; % pixels

hfov = vfov * img_width/img_height; 

fy = img_height * 0.5 / (tan (vfov * 0.5 * pi/180) );

fx = img_width * 0.5 / (tan (hfov * 0.5 * pi/180) );

% optical center
Ox = img_width/2.0; 
Oy = img_height/2.0;

% camera intrinsic matrix
K = [fx 0 Ox;
    0 fy Oy;
    0 0 1]; 
```
Notes: 

1. I specified field of view of 30 deg along y-axis in my XML (snippet below). You may use horizontal or diagonal fov parameters but your conversion formula would change accordingly. You'd be fine if your image size is a square. 
2. To verify, I calibrated Mitsuba rendered checkerboard pattern using MATLAB's camera calibration toolbox. Results are a match (approximate).

![image](https://user-images.githubusercontent.com/63920557/184660502-dbf8c7ef-101b-43cc-8889-b78f1c75b455.png)

**Comment by ram-bhaskara** [comment]
I just realized that the issue was about camera extrinsics. It is from the camera setup as put up in the below MATLAB function: 

`function R = cameraDCM(LookFrom, LookAt, up)
    
    LookAt = reshape(LookAt, [3,1]);
    LookFrom = reshape(LookFrom, [3,1]);
    up = reshape(up, [3,1]);
    
    zaxis = LookAt - LookFrom; % pointing in the camera plane 
    zaxis = zaxis./norm(zaxis);
    
    xaxis = cross(up, zaxis); 
    xaxis = xaxis./norm(xaxis); 
    
    yaxis = cross(zaxis, xaxis); 
    R = zeros(3,3);
    R = [xaxis, yaxis, zaxis];
   
end` 

For the translation vector, use the origin of your scene (your model will be placed at (0,0,0) I believe) and your LookFrom you get 
`translation_vec = origin - LookFrom;   % in inertial frame
t = R' * translation_vec;      % in my sensor coordinate frame`

Just be careful about the reference frame. Visualizing and analyzing from a simple render helped me. Our lab has our own rendering S/W that can also generate point clouds for optical navigation. Will hopefully update this thread once we solidify our code base.

**Comment by Speierers** [comment]
I opened a thread on this topic in the Mitsuba 3 Discussions page. Let's continue to chat about this over there, this is important for many users actually.

https://github.com/mitsuba-renderer/mitsuba3/discussions/174
