### ISSUE TITLE
[🐛 bug report] Setting "to_world" parameter works for shapes but not OBJMesh or PLYMesh

### ISSUE THREAD

**Issue by andrewilyas** [mitsuba-renderer/mitsuba2#292]
## Summary

I am trying to transform a shape after loading the scene from the XML. When this object is of type "Sphere" or "Cylinder," the following code works (see below for full code), in that the sphere is translated in ``im_after``:
```python
    im = render_torch(scene, params=params, spp=1, unbiased=True)
    axis = ek.scalar.Vector3f(1., 1., 1.)
    tx = ScalarTransform4f.translate(axis) 
    params['Sphere.to_world'] = tx
    params.set_dirty('Sphere.to_world')
    params.update()
    im_after = render_torch(scene, params=params, spp=1, unbiased=True)
```
However, if we change the object type to "ply" or "obj" and change ``Sphere`` in the above snippet to ``PLYMesh``, the object is in the same position in both images, and the transform seems to have no effect. 

I am using the ``gpu_autodiff_rgb`` variant.

## System configuration

- Platform: Ubuntu 16.04
- Compiler: clang
- Python version: 3.7
- Mitsuba 2 version: master
- Compiled variants:
    * `scalar_rgb`
    * `gpu_autodiff_rgb`

## Description / Steps to reproduce
```python
import torch
import enoki as ek
import mitsuba 
mitsuba.set_variant("gpu_autodiff_rgb")

from mitsuba.core import Thread, Bitmap, Struct, ScalarTransform4f
from mitsuba.core.xml import load_string
from mitsuba.python.util import traverse
from mitsuba.python.autodiff import render, write_bitmap, render_torch

import matplotlib as mpl 
mpl.use("module://imgcat")
from matplotlib import pyplot as plt 

sphere = """
<scene version='2.0.0'>
    <path value="/mitsuba2/resources/data/common"/>
    <integrator type="path">
        <integer name="max_depth" value="3"/>
    </integrator>

    <emitter type="constant" id="my_envmap">
        <float name="radiance" value="0.7" />
    </emitter>

    <shape type="ply">
        <string name="filename" value="meshes/teapot.ply"/>
        <bsdf type="plastic">
            <texture name="diffuse_reflectance" type="bitmap">
                <string name="filename" value="/wood.jpg"/>
            </texture>
        </bsdf>
    </shape>

    <sensor type="perspective">
        <transform name="to_world">
            <lookat origin="5, 5, 5"
                    target="0, 0, 0"
                    up="0, 1, 0"/>
        </transform>

        <float name="fov" value="40"/>

        <film type="hdrfilm">
            <string name="pixel_format" value="rgb"/>
            <integer name="width" value="224"/>
            <integer name="height" value="224"/>
        </film>

        <sampler type="independent">
            <integer name="sample_count" value="4096"/>
        </sampler>
    </sensor>
</scene>
"""

scene = load_string(sphere)
camera = scene.sensors()[0]
crop_size = camera.film().crop_size()

params = traverse(scene)
params.keep(['PLYMesh.to_world'])

im = render_torch(scene, params=params, spp=1, unbiased=True)
axis = ek.scalar.Vector3f(1., 1., 1.)
tx = ScalarTransform4f.translate(axis) 
params['PLYMesh.to_world'] = tx
params.update()
im_after = render_torch(scene, params=params, spp=1, unbiased=True)

write_bitmap('/im_before.png', im, crop_size)
write_bitmap('/im_after.png', im_after, crop_size)
```
Desired result: im_after.png has the teapot translated.

Actual result: im_after.png is identical to im_before.png

**Comment by Speierers** [comment]
Hi @andrewilyas ,

I would say that in the current codebase, accessing and modifying shape's transforms from the Python API isn't fully supported. In our experiments we have mostly been working with the vertex buffers directly.

Alongside support for `AnimatedTransform`, this is definitely on our TODO list.

The problem here is that for meshes, the transform is applied to the vertex positions in the constructor. Which means that in order to apply a new transform, you would first have to apply the inverse of the original transform and then the new transform.
ATM this isn't done in the `Mesh::parameters_changed()`. Moreover, `Mesh::parameters_changed()` only updates the BVH if the vertex positions were changed.

I suggest you take a look at the (this example)[https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_pose.py] on how to apply a transform to the `vertex_position_buf` directly in Python.

**Comment by andrewilyas** [comment]
Thanks, this worked!
