### ISSUE TITLE
[✨ feature request] Support for polarized diffuse reflection

### ISSUE THREAD

**Issue by akshatdave** [mitsuba-renderer/mitsuba2#331]
The Mitsuba2 paper mentions support for the pBRDF model by [Baek et al. 2018] that includes polarized specular and diffuse components. While the polarized specular component can be modelled by roughconductor, the support for polarized diffuse component seems missing from the current BSDF plugin. Would this polarized diffuse component be incorporated in the future releases? Also, what would be the simplest way to tweak the current plugin to model it? 

Thanks

 [Baek et al. 2018] Seung-Hwan Baek, Daniel S. Jeon, Xin Tong, and Min H. Kim. 2018. Simultaneous Acquisition of Polarimetric SVBRDF and Normals. _ACM Transactions on Graphics (Proceedings of SIGGRAPH Asia 2018)_ 36, 6 (2018).

**Comment by tizian** [comment]
Hi,
This is one of the features that did not survive one of the large refactoring steps Mitsuba 2 went through after writing the paper. Our recent updates on polarization were focused on measured pBSDFs and various fixes to the existing polarization implementation (see [here](https://github.com/mitsuba-renderer/mitsuba2/tree/polarbrdf-old), yet to be merged into the master branch). Adding this pBSDF model back into Mitsuba 2 is on my TODO list but I'm pretty busy with other ongoing projects so I can't make any promises unfortunately.
Conceptually, the implementation should be rather straightforward, but these pBSDF can be a bit tricky in practice because of the various coordinate and reference frame transforms that need to be applied in the Mueller-Stokes framework.

I'm attaching the previous implementation as a reference as it could serve as a good starting point. Note that:
1. This is from a pretty old version of Mitsuba 2, so some of the interfaces / template types worked differently.
2. The bugfixes on the `polarbrdf-old` branch mentioned above would need to be applied to this as well.
3. Looking at the code now, with a lot more experience of how to implement polarization, the coordinate system changes for the diffuse polarization doesn't look 100% convincing to me.

I hope that's helpful and I'd be happy to answer more questions.
Best,
Tizian

**Comment by tizian** [comment]
FYI: There is now a (work in progress) pull request for the diffuse + specular pBRDF that you mentioned: #402
