### ISSUE TITLE
- [🐛 bug report] Optix render

### ISSUE THREAD

**Issue by IvanVishnevskiy** [mitsuba-renderer/mitsuba2#333]
## Summary

I'm trying to render my scene with the following command:
`.\mitsuba.exe -m gpu_autodiff_spectral ..\Glass3.xml`
but it doesn't work

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Windows 10 2004
- Compiler: CMAKE 3.19
- Python version: 2.7.7
- Mitsuba 2 version: the lastest as of today
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `gpu_autodiff_spectral`
- GPU: GTX 1070
- CUDA: 10.2

## Description

I have exported a simple scene from blender with a glass + some whiskey (60k tris) and a specular plane + hdri
It works fine if I run it with scalar_spectral but when I try to do gpu rendering it tells me
`**Caught a critical exception: cuda_malloc(): out of memory!**`

I have read all the issues and I did drop my sample count to 16 (it was set to 256) as well as resolution from 1080p to 1/3 of that 
and now the error is as such:
`**Caught a critical exception: cuda_trace_append(): arithmetic involving uninitialized variable!**`

Here's a link to my final xml file: [https://drive.google.com/file/d/1tWdCn5RJ_9wAh1KbRBcpv9mK55Sr_GpT/view?usp=sharing](https://drive.google.com/file/d/1tWdCn5RJ_9wAh1KbRBcpv9mK55Sr_GpT/view?usp=sharing)

I can also say that Cycles in the OPTIX mode works just fine as well as Octane/Luxcore, allowing me to render 2x the 1080p res with undefined amount of samples.

## Steps to reproduce

1. Compile `gpu_autodiff_spectral`
2. run `.\mitsuba.exe -m gpu_autodiff_spectral ..\Glass3.xml` from the dist with my xml sitting one directory below

**Comment by Speierers** [comment]
Hi @IvanVishnevskiy ,

We are well aware that the current version of Mitsuba 2 on GPU quickly runs out of memory. This issue will be addressed in the upcoming major update.

In order to reproduce you issue, I will need access to the geometry files as well. Could you please package all the necessary files in a ZIP folder and share it here so I can take a look.

In the meantime, you could also try the following steps for debugging:
- reduce `max_depth` in the integrator. Try with 2, 4, 6, 8, 12, 16 to see if the error only occurs after a specific number of bounces
- switch every shape to `diffuse` to see if the issue comes from the materials
- Switch ON/OFF the emitters one by one to see if the issue comes from there

**Comment by IvanVishnevskiy** [comment]
[iv_meshes_textures.zip](https://github.com/mitsuba-renderer/mitsuba2/files/5583365/iv_meshes_textures.zip)
Oh, right, I forgot about these. Thank you for your answer, I will investigate your steps tomorrow

**Comment by vucenovic** [comment]
Hello,

I am running into the same problems, and am only able to render a resolution of 512px with a sample size of 10 per pixel. 
When is the new release update planned, that tackles this issue?

**Comment by Speierers** [comment]
Hi @vucenovic,

We haven't decided on a specific date yet, but we are making good progress. Hopefully in the coming month.

**Comment by vucenovic** [comment]
Thanks for the information, and good luck with the further implementation :)
