### ISSUE TITLE
Bitmap getdata() not exposed in Python

### ISSUE THREAD

**Issue by Harsharma2308** [mitsuba-renderer/mitsuba2#346]
I cannot access `data` data member from `Mitsuba.core.Bitmap` as of now. Probably this is not added yet?

**Comment by Speierers** [comment]
Hi @Harsharma2308 ,

The `mitsuba.core.Bitmap` Python bindings implement the Python [buffer protocol}(https://docs.python.org/3/c-api/buffer.html) this is why `.data()` isn't exposed. Note that you can also convert your `Bitmap` object into a numpy array as follow:

```python
    my_bitmap = compute_bitmap()
    np_bitmap = np.array(my_bitmap)
```

If this isn't enough for you, please provide a bit more context on how you would like to use this data pointer in Python.

Otherwise please close this issue ;)

**Comment by Harsharma2308** [comment]
Thanks this is exactly what I required.
