### ISSUE TITLE
[🐛 bug report] Vertex Positions Loss Backpropagating Incorrectly

### ISSUE THREAD

**Issue by nauman-tintash** [mitsuba-renderer/mitsuba2#348]
## Summary

*When I keep vertex positions buffer as optimization parameters, the loss is apparently being backpropogated incorrectly. Even if I keep the reference image and new image exactly the same, over a few iterations, the vertex positions keep getting updated and the loss keeps increasing.*

## System configuration

- Platform: Ubuntu 20.4
- Compiler: CMAKE 3.16.3
- Python version: 3.8.5
- Mitsuba 2 version: mitsuba-2 
- Branch : pathreparam-optix7 
- Compiled variants:
    * `scalar_rgb`
    * `gpu_autodiff_rgb`

## Description
Even if my source and target scene is exactly the same, if I keep the vertex positions buffer as differentiable parameter, the loss keep getting increased. Following is a sample of losses and corresponding images for the first 4 iterations from one example.

### Reference Render:
![ref](https://user-images.githubusercontent.com/12998475/101167168-53283580-365b-11eb-8db7-c2fca148149a.png)

Iteration 1 : (Loss = 4.21295e-16)
![ref](https://user-images.githubusercontent.com/12998475/101167168-53283580-365b-11eb-8db7-c2fca148149a.png)

Iteration 2 : (Loss = 0.000416789)
![it2](https://user-images.githubusercontent.com/12998475/101167810-4f48e300-365c-11eb-8e1d-757e8dc7ed06.png)

Iteration 3 : (Loss = 0.0170517)
![it3](https://user-images.githubusercontent.com/12998475/101167823-53750080-365c-11eb-8242-f3ef12a30168.png)

Following is my relevant code snippet : 
```
scene = load_file('bagel/scene.xml')
image_ref = render(scene, spp=2)

params = traverse(scene)
params.keep(['object.vertex_positions_buf'])
opt = Adam(params, lr=.02)

for it in range(iterations):
      image = render(scene, spp=2)
      ob_val = ek.hsum(ek.sqr(image - image_ref)) / len(image)
      ek.backward(ob_val)
      opt.step()
```

**Comment by Speierers** [comment]
Hi @nauman-tintash ,

This is strange indeed. At iteration 1, the loss you are getting is very small and I am surprised the first gradient step causes such a difference on iteration 2. Could it be that you're learning rate is too high?

Also it would be useful to verify that the two renders are indeed identical (e.g. use the same random numbers), otherwise a noise difference in the primal images would cause non-zero gradients. You could for instance run the following:
```python 
scene = load_file('bagel/scene.xml')
image_ref = render(scene, spp=2)
ob_val = ek.hsum(ek.sqr(image_ref - image_ref)) / len(image_ref )
```
to check whether `ob_val ==0.0` or if this is simply due to numerical imprecisions.

Another thing that comes to my mind is that the `pathreparam` integrator produces biased gradients (see publication for more info on that). This bias might affect such a simple case.

One last thing: in the provided optimization examples using the `pathreparam` integrator, we usually constraint the optimization problem (e.g. optimize translation, displacement along normals,...) to avoid creating invalid meshes with overlapping triangles. It looks like you 3rd iteration is already having this issue.

**Comment by Speierers** [comment]
You will most likely need to use the `pathreparam` integrator ([here](https://github.com/mitsuba-renderer/mitsuba2/pull/157)) in order to optimize geometry in Mitsuba 2.  This integrator will account for visibility discontinuities when differentiating the light transport simulation. Maybe this will solve you problem.

**Comment by HsiangYangChu** [comment]
> Does it works with this new code?

No! :( 
```
Traceback (most recent call last):
  File "sphere2cow.py", line 104, in <module>
    ek.backward(ob_val)
RuntimeError: set_gradient(): no gradients are associated with this variable (a prior call to requires_gradient() is required.)

```

**Comment by Speierers** [comment]
Please take a look at [this one](https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_heightfield.py)

**Comment by HsiangYangChu** [comment]
> Please take a look at [this one](https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_heightfield.py)

It seems that the folder `scene_folder` is lost:
```
(mt) hsiangyangchu@zhuxiangyang-System-Product-Name:~/mitsuba2/docs/examples/10_inverse_rendering$ python invert_heightfield.py 
2021-10-11 20:22:34 INFO  main  [optix_api.cpp:56] Dynamic loading of the Optix library ..
Traceback (most recent call last):
  File "invert_heightfield.py", line 35, in <module>
    scene = xml.load_file(scene_folder + 'scene.xml')
RuntimeError: ​[xml.cpp:1180] "../../../resources/data/docs/examples/invert_heightfield/scene.xml": file does not exist!
```

**Comment by binorchen** [comment]
Hello @HsiangYangChu @Speierers ,

Have you solved this problem? I am suffering exactly the same problem.

Thank you!
