### ISSUE TITLE
AOV Integrator bitmap channels [❔ other question]

### ISSUE THREAD

**Issue by akonneker** [mitsuba-renderer/mitsuba2#351]
## Summary

When using the aov integrator, and converting the MultiChannel type bitmap output to a numpy array, I always get 3 + 3*n channels, where n is the number of AOV outputs requested. 

## Description

I'm trying to test out the AOV integrator for generating depth images of a scene, but the output of the multichannel bitmap when converted to a numpy array is odd. I'm using the scalar_mono variant.
When using the following simple aov integrator, I would expect a single channel output which contains the depth values (WxHx1).
`<integrator type="aov">
    <string name="aovs" value="Z:depth"/>
</integrator>`

Instead, I get an [WxHx6] dimensional output. If I call the develop method to create an exr image, I can examine the header and see 5 channels: RGBA + Z, the requested depth channel (The RGBA strikes me as odd, since I used the mono variant and also explicitly set the hdrfilm plugin to use luminance for the pixel_format). If I add another output (say, normals) it will add another 3 channels to the output.

So I have 2 questions:

1. Why is there always an RGBA image being generated?
2. Why does the depth data occupy 3 channels when converted to a numpy array, but a single channel when converted to an exr?

**Comment by Speierers** [comment]
Hi @akonneker ,

Have you tried to use the `.split()` method of the bitmap class? This will return a list of bitmap objects that you can then convert into numpy arrays.

To be honest, the `mono` variant hasn't been thoroughly tested and it might well be that the `develop()` method doesn't work as expected in those cases. I will take a closer look once I am done with my current work items.

**Comment by irinaciortan** [comment]
Hello!
Since I think my issue is somewhat similar, I decided not to open a new issue and write it here.
I'm trying as well to generate the normal map of a ply mesh (that has no color included, only geometry). I'm using the same aov integrator, but my image is completely blank (full of zeros). I tried rendering with both spectral and rgb variants. Also, I tried adding a "path" subintegrator, in which case I do get the contour of the object, all in black in the alpha channel. However, the image has only 4 channels, there are no additional channels for the normal. Are you aware if this kind of issue has been raised before? I would like to know what I'm doing something wrong on my end. I attached the scene file, plus the two exr images (without path and with path integrator).

Very grateful for your help!!!
[debug.zip](https://github.com/mitsuba-renderer/mitsuba2/files/6500036/debug.zip)

**Comment by Speierers** [comment]
Hi @irinaciortan ,

I think the issue is that you are not visualizing the exr image with the right tool ;)

Using [tev](https://github.com/Tom94/tev), I can see the different channels in the EXR, e.g. the shading normals:

![image](https://user-images.githubusercontent.com/6662561/118782732-b1a24280-b88e-11eb-9338-035d1741a5b3.png)
