### ISSUE TITLE
- [❔ I would like to ask if this software supports the common maps. If not, how to support them such as Ambient Occlusion or Displacement/Height. 

### ISSUE THREAD

**Issue by litc-rgb** [mitsuba-renderer/mitsuba2#363]
The common maps are as follows：
（1）Diffuse/Albedo/Basecolor
（2）Reflection/Specular
(3) Metalness
(4) Glossiness
(5) Roughness
(6) Normal
(7) Displacement/Height
(8) Bump
(9)Ambient Occlusion

This software currently supports two kinds of map BSDF adapters after I read the document about mitsuba2:
Bump map BSDF adapter (bumpmap)
Normal map BSDF (normalmap)

Now,I would like to ask if this software supports the common maps. If not, how to support them such as Ambient Occlusion or Displacement/Height.

**Comment by merlinND** [comment]
Hello @litc-rgb,

As far as I can tell, the parameters that you mention correspond to parameters of a Disney / "principled" BSDF. It is not currently supported, but we would definitely like to have it in Mitsuba 2 (see #153). PRs are welcome if you would like to give a shot at implementing it.
Likewise for displacement / heightmaps.

Regarding ambient occlusion, since it is not a physically based effect, I don't believe that we will support it.
