### ISSUE TITLE
- [❔ other question] Why the value of phase function is only applied to emitter sampling?

### ISSUE THREAD

**Issue by gcmiao** [mitsuba-renderer/mitsuba2#387]
In Mitsuba 1, the VolumetricPathTracer accumulates the value of phase function on throughput.
https://github.com/mitsuba-renderer/mitsuba/blob/master/src/integrators/path/volpath.cpp#L158

But it cannot be found in Mitsuba 2's VolumetricPathIntegrator. The value of the phase function is only applied to emitter sampling.
https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/integrators/volpath.cpp#L166

Could you explain more about this? Thank you!

**Comment by dvicini** [comment]
Hi, 
This is because all the currently supported phase functions in Mitsuba 2 have perfect importance sampling, where the ratio of phase function value and pdf after sampling is 1. So there is no need to multiply with any value. This will need to be adapted if we want to support more complex phase functions, which do not admit perfect importance sampling (e.g. because they are spectrally varying)
