### ISSUE TITLE
- [✨ feature request] Why roughplastic's alpha is not differentiable?

### ISSUE THREAD

**Issue by LZleejean** [mitsuba-renderer/mitsuba2#440]
## Summary

Everything is ok but can't optimize roughplastic's alpha.

## Description

I tried create two parameters to be optimized which is roughness and diffuse reflectance but failed. Because roughplastic's alpha is not differentiable.

**Comment by Speierers** [comment]
Hi @LZleejean ,

Please see #391 for this.

Basically those are not differentiable as the roughplastic BSDF pre-computes tables in its constructor, which would need to be updated whenever you update the `alpha` value. We are still investigating better solutions to also make this parameter spatially-varying.

This being said, with only a few changes, you should be able to turn this member into a differentiable type (`ScalarFloat -> Float`), expose it in the `RoughPlasticBSDF::traverse` call back and move the table computation code to `RoughPlasticBSDF::parameters_changed()` so that it gets updated when necessary.

Good luck!
