### ISSUE TITLE
[❔ other question] How to calculate emitter ray hit mask?

### ISSUE THREAD

**Issue by mehrab2603** [mitsuba-renderer/mitsuba2#456]
I was wondering how I can calculate a mask that indicates which points in the scene are reachable from a particular light source.

![emitter_spot_no_texture](https://user-images.githubusercontent.com/5913653/124228769-e6c6c500-dac9-11eb-9875-637cc7026703.jpg)

For example, for the above scene, I would like to calculate a mask for the red projection light source which should be true for all the points in the scene that were hit by the light rays from this emitter (e.g. the points on and around the ball) and false for all other points (e.g. the left shadow behind the ball and all other points where there is negligible/no contribution from the red light source).

**Comment by Speierers** [comment]
Hi @mehrab2603 ,

You will need to implement you own integrator for this. See for instance the `depth` integrator as a starting point. You could for instance trace a ray from the first surface interaction towards the specific light. This can be done using the `emitter->sample_position(..)` method and then `si.spawn_ray_to(..)` to create the ray. If the contribution is greater than zero, then you return a `1.0`, and a `0.0` otherwise.

The index of the light source could be specified in the `props` object so you can easily generate such masks for the different light sources.

**Comment by mehrab2603** [comment]
@Speierers Got it. Thanks!
