### ISSUE TITLE
[🐛 bug report] unreferenced property ["density"] in medium plugin of type "homogeneous"

### ISSUE THREAD

**Issue by ankus-wu** [mitsuba-renderer/mitsuba2#478]
## Summary

When using volpath to render cbox with medium, it shows this error: `unreferenced property ["density"] in medium plugin of type "homogeneous"`

## System configuration

- Platform: Win10
- Compiler: cmake 
- Python version: 3.8.8
- Mitsuba 2 version: 2
- Compiled variants:
    * `scalar_rgb`
    * `packet_rgb`
    * `gpu_rgb`
    * `gpu_autodiff_rgb`

## Description

I am not sure whether it's because of the version of mitsuba, or lack of any variants. I'd appreciate it if you can help me with this.

## Steps to reproduce

1. I used the example from https://gist.github.com/dvicini/d0e219bc7dadbd949cfab177c9fcef17, also tried another one from #76 , got the same problem.

**Comment by merlinND** [comment]
Hi @ankus-wu,

The `homogeneous` plugin does not expect a `density` property but `sigma_t`:

https://github.com/mitsuba-renderer/mitsuba2/blob/b92ddc234d1cb3510cba4db1601cd7f03e65a138/src/media/homogeneous.cpp#L23-L27

You can use the test scenes as reference, since the gist you linked was probably written for a different Mitsuba version.

https://github.com/mitsuba-renderer/mitsuba-data/blob/d40d342c250b36b78ccf842e629783cf74692ea1/tests/scenes/participating_media/test_homo_area_light.xml#L6-L11
