### ISSUE TITLE
[❔ other question] Not enough registers warning

### ISSUE THREAD

**Issue by saeedhd96** [mitsuba-renderer/mitsuba2#479]
## Summary

Not enough registers causing very slow computation

## Description

Hi,

In mitsuba2, broken branch, on mode CUDA_rgb, I keep getting the below warning when my scenes are just a little bit complex and I am trying to use mesh.sample_position() to sample positions on the surfaces:

_The compiled kernel requires more registers than what is natively available, and some of the associated memory had to be spilled into global memory. This is costly and will impact performance. You may want to partition your computation into smaller pieces to avoid this._

How can I get around this issue? Even with a very small wavefront size, I get this. What else could help me?

**Comment by Speierers** [comment]
Hi @saeedhd96 ,

The `mitsuba:broken` branch is very unstable and buggy (hence the name) and isn't maintained anymore. Until the upcoming release, I would recommend you stick with the `master` branch, otherwise you will be on your own to debug those issues unfortunately.

Regarding your issue, it could be that the kernel generated is too long. You could try to break it down in smaller chunk, e.g. using `ek.eval()`. For instance when using C++/Python for loops, make sure every iteration create it's own kernel.

Good luck!

**Comment by saeedhd96** [comment]
Hi,

Thanks for your response! Regarding the issue, you mean calling just `ek.eval()` at every for loop in python would divide the kernel? I added that line to my loops and still the warning shows up. This happens with the scenes that have a lot of meshes in their description. Like the Staircase or the Country Kitchen here:
https://benedikt-bitterli.me/resources/
It doesn't happen with so many of the scenes there like the dining room or the living room.

**Comment by Speierers** [comment]
Does this message occur when loading the scene or when rendering?

**Comment by saeedhd96** [comment]
This pops up when I call `shapes_ek.sample_position() `in a loop. `shapes_ek` is an enoki array of `Shape` data structure(wenzel added that for me in `broken`. Due to such kind of functionalities in `broken` I cannot leave it for now!).
I added `ek.eval()` in the begining of the loop. Still after a few number of iterations, it pops up.
