### ISSUE TITLE
[✨ feature request] [❔ other question] Batched rendering and backpropagation

### ISSUE THREAD

**Issue by Daiqy** [mitsuba-renderer/mitsuba2#482]
Hi, I am now doing my research project based on your excellent work!
I am wondering whether mitsuba2 supports batched rendering and backpropagation (i.e. a list of scene, and the corresponding list of camera and light source). It might be essential for training and optimizing a differentiable rendering method on PyTorch.
If mitsuba2 does not support it, could you provide some tips on how I can implement this by myself?
Thanks and regards!

**Comment by merlinND** [comment]
Hi @Daiqy,

What you describe is not supported out of the box, but rendering from multiple cameras at once should be fairly easy to implement by modifying the following Python function to sample rays from multiple cameras instead of just one:

https://github.com/mitsuba-renderer/mitsuba2/blob/b92ddc234d1cb3510cba4db1601cd7f03e65a138/src/python/python/autodiff.py#L35-L42

Note that GPU memory usage is often a limiting factor with autodiff + path tracing, so I would advise trying first with a single camera to check which image resolution and spp your GPU can fit. Memory usage will be improved significantly in the next release.

As for rendering multiple scenes at once, I believe the only way would be to start multiple Mitsuba processes in parallel.
However, if you render with path tracing, one scene and a few cameras will probably be enough to saturate a GPU.

Hope this helps!
Merlin
