### ISSUE TITLE
[❔ other question] BSDF sampling with Beckmann distribution

### ISSUE THREAD

**Issue by MaximilianBader** [mitsuba-renderer/mitsuba2#495]
## Summary
Mismatch between histogram of sampled microsurface normals for scattering BSDF in mitsuba and underlying Beckmann PDF

## Description
I investigated the sampling of microsurface normals according to the Beckmann distribution for BSDF sampling. The implementation in ``mitsuba2/include/mitsuba2/core/warp.h`` (lines 496-518) matches the proposed sampling strategy in the referenced paper (Eq. (35), p. 201, Walter et. al., 2007). However, when I plot the Beckmann PDF (see attached figure, top left image) or the Facet distribution D (see attached figure, top right image) and compare it to a histogram of sampled microsurface normal angles $\Theta_m$ (see attached figure, bottom right image), they do not match.
In my opinion, the sampled microsurface angles $\Theta_m$ are reasonable, because I'd expect a mean angle $>0$ for a scattering surface. However, as the sampling strategy is derived from the Beckmann distribution mathematically, I'm a little worried. Could you elaborate, why the sampling strategy in mitsuba2 is valid and give details, how it was derived?

![Beckmann_sampling](https://user-images.githubusercontent.com/43639142/132844908-784fe41d-9f49-4f6c-b9ae-0bde58814a04.png)

**Comment by tizian** [comment]
I'm not 100% sure I understand the question.
Are you concerned about the slight offset of the two histograms in the bottom right plot? You should be able to get a closer match if you draw more samples here.

Or are you wondering about the difference between the bottom left and bottom right plot? If I understand your setup correctly, this is due to a conversion factor between unit vectors and spherical coordinates. I.e., histogram on the bottom right has an implicit \sin\theta scale factor.
A derivation of the sampling routine can be found here: https://www.pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Sampling_Reflection_Functions#MicrofacetBxDFs

**Comment by MaximilianBader** [comment]
Hi @tizian,

No I was actually not concerned about the variance in histograms on the bottom right. I was concerned by the mismatch between the Beckmann facet distribution function (plotted in the top right image) and the histogram of sampled angles (plotted in the bottom right image). Thanks for mentioning the scaling factor $sin(\theta)$. I have only read about a scaling with $cos(\theta)$  so far. I'm quite sure the derivation in the PBR book will provide the desired clarification. So I'll close the issue for now. If I encounter additional troubles, I'll just reopen it again and reach out.

Thanks for your quick response! 😄
