### ISSUE TITLE
[❔ other question] Transform of Sensors in ParameterMap

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba2#500]
## Summary

I've encountered a situation where I need to programmatically set the camera position in a given scene. Normally for other scene parameters, I would use the `mitsuba.python.util.traverse` function and update the resulting `ParameterMap`, but for sensors there is no corresponding `transform` property like there is for e.g. `bitmap` and `checkerboard` nor another set of properties that would enable manipulating the camera origin, view direction and up directions.

Reloading the scene for each new camera position is too slow since I am loading volume data as well and would like to avoid having to reload that as well.

## System configuration

- Mitsuba 2 version: 1ed2009f98d7f3f1789dce527169710496b3a4b9

**Comment by Speierers** [comment]
Hi @Microno95 ,

Unfortunately this is not currently supported in the current codebase. You can try to add this yourself by editing the `parameters_changed()` and `traverse()` method of your sensor, but this will likely require further changes across the codebase.

Also note that in order to differentiate this parameter, you will need to properly handle visibility discontinuities in the integrator.

**Comment by merlinND** [comment]
To add on to what @Speierers wrote, I think it should be quite feasible to add this yourself. Just make sure that all internal / precomputed variables in the sensor get updated in `parameters_changed()` after updating the transform. If you're not changing the fov and just applying translations & rotations, it should work without too much trouble.
