### ISSUE TITLE
[❔ other question] How to optimize textures using mitsuba2?

### ISSUE THREAD

**Issue by joy-alen** [mitsuba-renderer/mitsuba2#534]
Hi, I would like to know whether it is possible to optimize textures of an object as in the presentation of "Reparameterizing discontinuous integrands for differentiable rendering", where optimization of texture and shape are done. The examples provided for inverse rendering are for estimating a single reflectance value for the entire object as in the case of cbox. I'm kind of new to this so any help is appreciated.

Thank you.

**Comment by stefanjp** [comment]
You could look at following example, where an environment map is optimized. Optimizing for instance the 'reflectance' texture of the 'diffuse' BSDF is very similar. Just reset the '[...].reflectance.data' and also use it for optimization instead of 'my_envmap.data'.

https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/advanced.html

**Comment by Speierers** [comment]
Indeed @joy-alen, you should take a look at the [example mentioned](https://mitsuba2.readthedocs.io/en/latest/src/inverse_rendering/advanced.html) above. 

You should be able to combine it with this other [example script](https://github.com/mitsuba-renderer/mitsuba2/blob/70af33ff4d69e6d14205f1826d63c9cf0bdcb639/docs/examples/10_inverse_rendering/invert_heightfield.py) in order to jointly optimize a shape and a texture as done in the paper.

Good luck!

**Comment by joy-alen** [comment]
Thank you for the suggestions and the example scripts.
