### ISSUE TITLE
[❔ other question] Optimize microfacet orientation for anisotropic brdf models

### ISSUE THREAD

**Issue by stefanjp** [mitsuba-renderer/mitsuba2#548]
## Summary

Is there a way in Mitsuba 2 to specify and optimize the orientation of the microfacets for anisotropic BRDF models?

## Description

I would like to learn the orientation of microfacets along with roughness in tangential and bitangential direction for the rough conductor BRDF, to learn the material parameters for e.g. a radial brushed metal:
![image](https://user-images.githubusercontent.com/315302/146557113-909f216b-c76f-4a24-b752-2a148361155f.png)

**Comment by Speierers** [comment]
Hi @stefanjp,

Yes this should be possible. E.g. for meshes you will need to optimize the UV mapping (`mesh.vertex_texcoords`) as it is its partial derivative that provide the tangential and bitangential directions. (see `SurfaceInteraction::compute_uv_partials`)

Another solution would be to implement a custom BSDF that reads those directions from a 2D texture directly.

Then you should also jointly optimize for the `alpha_u` and `alpha_v` parameters of the BSDF.

Be aware that discontinuities in the simulation due to changes in the roughness parameters might yield incorrect gradients. For more information on this, please take a look at our [SIggraph paper from last year](https://rgl.epfl.ch/publications/Zeltner2021MonteCarlo).

Good luck!

**Comment by stefanjp** [comment]
Hi @Speierers,

thank you for your valuable input. I wanted to leave a comment on my follow up work. I have been reading your interesting Siggraph paper and could partly reproduce your results of the "veach" scene.

To solve my problem I have started by trying to optimize the `mesh.vertex_texcoords` which did not work in a scene with Roughconductor BSDF of a simple mesh and an environment map emitter. No gradients have been caluclated for `vertex_texcoords_buf`. If I remember correctly I used the path integrator.

To modify the anisotropic direction, I have implemented a plugin that allows me to rotate `si.wi` (incoming direction) and `wo` (outgoing direction) for the BSDF querys (`pdf`, `sample` and `eval`). I based by plugin on the bumpmap plugin which changes the shading frame and transforms `si.wi` and `wo` to fit that new shading frame. I do not modify the shading frame and rotate both `si.wi` and `wo` around the shading normal. So far the results seem ok. A rendering with a single spotlight on a sphere gave me comparable results to blender. I will do experiments to optimizing the anisotropic direction. If everything works out as expected and someone is interested, I can leave the code for anisotropic rotation here.
