### ISSUE TITLE
[❔ other question] Calculation of cos_theta_t_sqr difference between float and complex versions?

### ISSUE THREAD

**Issue by hakanai** [mitsuba-renderer/mitsuba2#555]
## Summary

I was trying to get my head around the fresnel calculations and found what appears to be an inconsistency which I'm trying to rationalise.

## Description

Current code for computing `cos_theta_t_sqr` for non-complex case:

```
    Float cos_theta_t_sqr =
        fnmadd(fnmadd(cos_theta_i, cos_theta_i, 1.f), eta_ti * eta_ti, 1.f);
```

`fnmadd(a,b,c)` is equivalent to `-a*b - c` according to Enoki docs. So,

fnmadd(fnmadd(cos_theta_i, cos_theta_i, 1.f), eta_ti * eta_ti, 1.f)
= fnmadd( ( -cos_theta_i * cos_theta_i - 1 ), eta_ti * eta_ti, 1 )　　　_(expanding fnmadd)_
= -( -cos_theta_i * cos_theta_i - 1 ) * (eta_ti * eta_ti) - 1　　　_(expanding fnmadd)_
= -( -cos_theta_i^2 - 1 ) * (eta_ti^2) - 1　　　_(rewriting squares)_
= (cos_theta_i^2 + 1) * (eta_ti^2) **-** 1　　　_(resolving double -)_

Code for complex case:

```
    Complex<Float> cos_theta_t_sqr =
        1.f - sqr(eta_ti) * fnmadd(cos_theta_i, cos_theta_i, 1.f);
```

So for this one,

1.f - sqr(eta_ti) * fnmadd(cos_theta_i, cos_theta_i, 1.f);
= 1 - (eta_ti^2) * ( -cos_theta_i * cos_theta_i - 1 )　　　_(expanding fnmadd)_
= 1 - ( -cos_theta_i * cos_theta_i - 1 ) * (eta_ti^2)　　　 _(flipping *)_
= - ( -cos_theta_i^2 - 1 ) * (eta_ti^2) + 1　　　_(moving 1 to end)_
= (cos_theta_i^2 - 1) * (eta_ti^2) **+** 1　　　_(resolving double -)_

So one of the equations resolves to (bunch of stuff) **-** 1 while the other resolves to (bunch of stuff) **+** 1.

This confuses me... are the two equivalent somehow or did I make a mistake somewhere?

**Comment by hakanai** [comment]
If I run this from first principles,

cos²θt = 1 - sin²θt　　　(trig identity)
= 1 - sin²θi . n²　　　(Snell's Law)
= 1 - ( 1 - cos²θi ) . n²　　　(trig identity)
= 1 + ( cos²θi - 1 ) . n²　　　(flipping minus)

**Comment by wjakob** [comment]
There is a mistake in your interpretation of `fnmadd` (or in our docs?). ``fnmadd(a,b,c)`` is equivalent to ``-a*b + c``. What you described would be `fnmsub`.

**Comment by hakanai** [comment]
ah, it's -a*b+c... and no, I think the docs are right too, I must have been reading docs of something else where it had the opposite meaning. (facepalm)

**Comment by wjakob** [comment]
no worries, as always it's good to have extra eyes on things.

**Comment by hakanai** [comment]
I was looking at the code to try and understand how to generate Mueller matrices for reflection and refraction. The one thing I've been unable to explain in the science is this `factor`:

https://github.com/mitsuba-renderer/mitsuba2/blob/1ed2009f98d7f3f1789dce527169710496b3a4b9/include/mitsuba/render/mueller.h#L209-L210

essentially, some factor = -ηᵢₜ (cosθt/cosθt)

In my own ray tracer, I'm looking at the equations in Boundary and Interface Conditions for Polarized Radiation Transport in a Multilayer Medium, R. D. M. Garcia (2011), which come out like this:

            //         n₂cosθi - n₁cosθt            n₁cosθi - n₂cosθt
            // R_par = ───────────────── ,  R_ort = ─────────────────
            //         n₂cosθi + n₁cosθt            n₁cosθi + n₂cosθt
            //
            //             2n₁cosθi                     2n₁cosθi
            // T_par = ───────────────── ,  T_ort = ─────────────────
            //         n₂cosθi + n₁cosθt            n₁cosθi + n₂cosθt

And then the matrices both look like this:

            // ⎡  ½ (par par^ + ort ort^)  ½ (par par^ - ort ort^)   0           0            ⎤
            // ⎢  ½ (par par^ - ort ort^)  ½ (par par^ + ort ort^)   0           0            ⎥
            // ⎢  0                        0                         R(par ort^) I(par ort^)  ⎥
            // ⎣  0                        0                        -I(par ort^) R(par ort^)  ⎦

They multiply the transmission matrix by a "transmission factor", which I thought, okay, this is sounding like it will match up, but _their_ formula for the transmission factor is:

            //         ⎧ n₂ ⎫³ ⎧ cosθt ⎫
            // f_T   = ⎪ ── ⎪  ⎪ ───── ⎪
            //         ⎩ n₁ ⎭  ⎩ cosθi ⎭

So essentially η³ instead of -η.

I'd love to know where this discrepancy comes from but it could just be that the factor was derived differently in another paper.

In my system, I'm also fighting to keep the complex arithmetic in the picture because the formulae make a lot more sense with the complex arithmetic kept in place. (Performance worries I am delaying for later.) So I'm trying to figure out how this transmission factor works given that three of the things in the equation are complex-valued. :(

**Comment by tizian** [comment]
Hi @hakanai,
There's two things to this:

1) The "missing" `eta^2` factor is accounted for on the BSDF level, (e.g. in `dielectric.cpp`). That's because some rendering algorithms (depending on whether they trace paths starting from lights or the camera) need to cancel this factor out again.

2) The negative sign seems more tricky. I think I've double checked every single minus sign for the polarization code at least once, but I don't actually think I've ever looked at this one in particular. It also seems to be around since the very beginning (it was introduced ~4 years ago by @wjakob).
The current implementation is validated against the Mueller matrices computed by [ART](https://cgg.mff.cuni.cz/ART/), which gives me some confidence. But I also can't find this minus sign in any of the equations, so you might be on to something important!
A particularly nasty detail here is also that such a bug would not cause issues in almost any case, because light will always refract in and then out of a material again, hence cancelling out any sign mistake that affects the whole matrix.

I'd be very curious if you have more info about this, or potentially an idea to verify the correctness once and for all.
The paper you linked seems to be quite clear about everything---but unfortunately it also mixes up the transmission amplitudes (Eq. 7c and 7d) compared to all other references I've seen before, so I'm not totally convinced. (And this alone does not explain the sign issue in question here.)

Best,
Tizian

**Comment by tizian** [comment]
Apologies---I've looked at this all wrong I think.

1. The seemingly missing negative sign is cancelled out by this logic here: https://github.com/mitsuba-renderer/mitsuba2/blob/4e7628c6eed365904ca2ba536b795d1b03410344/include/mitsuba/render/fresnel.h#L183
This is pretty important for the case where light is refracted _out_ of a dielectric with `cos_theta_i < 0`. Some formulations of the Fresnel equations/Mueller matrices I think don't handle this case, and instead assume `cos_theta_i > 0` but `eta -> 1/eta`.

2. Eq. 7c and 7d in the referenced paper actually are correct.

With this, I think everything is actually matching as it should. But please do let me know if something still seems fishy to you.

- Tizian

**Comment by hakanai** [comment]
Yeah, everything makes a lot more sense now.

In my own system, I don't have negative angle of incidence because in that situation I flip the normal instead, so I think I have it a little easier in the code as a result.
