### ISSUE TITLE
Degree of linear polarization (dolp) for diffuse and conductor materials

### ISSUE THREAD

**Issue by Seasandwpy** [mitsuba-renderer/mitsuba2#584]
- [❔ other question]

## Summary

Hi, I used the stokes integrator and found out the diffuse and conductor objects don't have polarization effect. The dolp of the objects are 0. As far as I understand, the dolp should be larger than 0 because there should be diffuse polarization for diffuse objects and specular polarization for conductor objects. The dielectric and pplastic materials seem to be working fine. Therefore I would like to ask if the diffuse and conductor materials are not suitable for polarization simulation in the current version?

**Comment by tizian** [comment]
* The `diffuse` material doesn't support polarization by design: it is supposed to be an idealized Lambertian material which acts as a perfect depolarizer. However, you should be able to adapt `pplastic` to your needs in case you are interested in diffuse polarization _without_ any specular component.

* The `conductor` should cause all kinds of linear and circular polarization states however. We studied this one quite extensively and even compared it against some real-world measurements at some point. Could you post a minimal scene/script that reproduces your problem so I can double check? Thanks!

Best,
Tizian

**Comment by Seasandwpy** [comment]
[minimal_scene.zip](https://github.com/mitsuba-renderer/mitsuba2/files/8416534/minimal_scene.zip)
Sure, the zip file contains the scene and python script. The s1 and s2 are all zeros in the debug mode.

**Comment by tizian** [comment]
Ah, I think I see the problem. You need to either specify a (complex) index of refraction, or one of the built-in conductor materials for those BSDFs. See the documentation [here](https://mitsuba2.readthedocs.io/en/latest/generated/plugins.html#smooth-conductor-conductor). In case none of this is set explicitly, Mitsuba will fall back to the "none" material, which is an idealized mirror without any Fresnel function applied at all.

**Comment by Seasandwpy** [comment]
thanks, the dolp shows up after adding the material part. I didn't find stainless steel in the material list,  but I found the refractive index and extinction coefficient  (2.75681 and 3.792016) on the website. Are the two coefficients the real and imaginary part of IOR used here?

**Comment by tizian** [comment]
`eta` is the real part, `k` the imaginary one.
