### ISSUE TITLE
White noise in spectral rendering - [❔ other question]

### ISSUE THREAD

**Issue by Ine-123** [mitsuba-renderer/mitsuba2#643]
## Description

I want to create a simulation of apple tissue based on the bulk optical properties (absorption coefficient, scattering coefficient and anisotropy factor). I used this code for the scene, but get always white noise (fireflies?). I already tried changing some parameters (different integrators, higher sample count, brighter light source) but it doesn't seem to help. Anyone suggestions?

![Apple](https://github.com/mitsuba-renderer/mitsuba2/assets/152627223/cfc7f22e-b684-4671-92b9-351ed384f13c)

```

 <?xml version='1.0' encoding='utf-8'?>
 
 <scene version="0.6.0">
    <integrator type="volpath"> 
        <integer name="maxDepth" value="100"/>
    </integrator>

    <shape type="obj">                                  
        <string name="filename" value="appleFilled.obj"/>
        <transform name="toWorld">
			<translate x="0" y="0" z="0"/>
            <scale value="1.0" />
        </transform>

        <medium name="interior" type="homogeneous">
			<spectrum name="sigmaS" filename="sigmaS.csv"/>
			<spectrum name="sigmaA" filename="wl_mu_a.csv"/> 
			<phase type="hg">
				<float name="g" value="0.8313"/>
			</phase>
        </medium>
 
        <bsdf type="roughdielectric">
            <string name="distribution" value="beckmann"/>
            <float name="alpha" value="0.304"/>
            <float name="intIOR" value="1.33"/>
            <float name="extIOR" value="1.0"/>
        </bsdf>
    </shape>

	
    
	<sensor type="perspective">     <!--sensor-->
		<float name="focusDistance" value="6"/>
		<float name="fov" value="40"/>
		<string name="fovAxis" value="x"/>
		<transform name="toWorld">
			<lookat target="0, 0, 0" origin="0, 0, 0.2" up="0, 1, 0"/>
		</transform>
 
        <sampler type="independent">
            <integer name="sampleCount" value="128"/>
        </sampler>
 
        <film type="hdrfilm">
            <boolean name="banner" value="true"/>
            <integer name="height" value="768"/>
			<integer name="width" value="768"/>
            <string name="pixelFormat" value="spectrum"/>
            <rfilter type="gaussian"/>
        </film>
    </sensor>

    
    <emitter type="directional">
        <transform name="toWorld">
            <lookat origin="0,0,0.3" target="0.1, 0, 0" up= "0,1,0"/>   
        </transform>
    </emitter> 

  
</scene>
```

**Comment by njroussel** [comment]
Hi @Ine-123 

Disclaimer: as mentionned in the README this repository is now deprecated. We only maintain [Mitsuba 3](https://github.com/mitsuba-renderer/mitsuba3).

I doubt this is an actual bug in the renderer but rather an issue with your scene. I'd incrementally build/change your scene to understand what is producing the fireflies. The current issue might be caused by the dielectric, the volume, the shape, the number of bounces int the integrator... Try figuring out which one(s) it is. Just from the scene description, it is hard to help you any further.

I'd suggest you upgrade to Mitsuba 3 in any case. We'll help you if you open an issue/discussion in [its repository](https://github.com/mitsuba-renderer/mitsuba3).
