### ISSUE TITLE
volpath / volpathmis in gpu / gpu-autodiff mode

### ISSUE THREAD

**Issue by dnageo** [mitsuba-renderer/mitsuba2#98]
I am using the minimal example from #76 and have some issues running the volpath / volpathmis integrators in GPU as well as GPU-autodiff modes. 

Setup:
- xml as posted in #76
- commented out the following, as rectangle seems not to be implemented on GPU
```
 <!--
    <shape type="rectangle">
        <bsdf type="diffuse">
            <spectrum name="reflectance" value="0.5"/>
        </bsdf>
    </shape>
    -->
```
- *.obj as posted in #76
- Driver Version: 440.64.00
- Cuda 10.1
- Optix 6.5

I am able to run in `scalar_rgb` and `packet_rgb`  modes, however, `gpu_rgb` and `gpu_rgb_autodiff` fail:

```
020-04-21 11:27:27 INFO  main  [xml.cpp:1146] Loading XML file "./test_volpath_github_issue_76.xml" ..
2020-04-21 11:27:27 INFO  main  [xml.cpp:1147] Using variant "gpu_autodiff_rgb"
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/uniform.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/volpathmis.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/hdrfilm.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/gaussian.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/independent.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/perspective.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/constant.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/isotropic.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/homogeneous.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/constvolume.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/null.so" ..
2020-04-21 11:27:27 INFO  main  [PluginManager] Loading plugin "plugins/obj.so" ..
2020-04-21 11:27:27 INFO  main  [Scene] Validating and building scene in OptiX.
Traceback (most recent call last):
  File "/repositories/mitsuba2/scripts/volpath_test/render_volpath_test.py", line 44, in <module>
    scene.integrator().render(scene, sensor)
RuntimeError: cuda_trace_append(): arithmetic involving uninitialized variable!
```

Furthermore, the I have the following questions, regarding the volumetric renderer:
- Is volpath-simple now called volpathmis?

- Is the above a bug, or is there no GPU implementation yet? And if the latter holds true, will there be a GPU-implementation, and a GPU-autodiff implementation in the near future?

Thank you very much for your answers in advance!

Finally, I found that the doc should be updated, in the section for `Smooth dielectric material ` you state an example for a medium within a dielectric material: 

```
<shape type="...">
    <bsdf type="dielectric">
        <float name="int_ior" value="1.504"/>
        <float name="ext_ior" value="1.0"/>
    </bsdf>

    <medium type="homogeneous" name="interior">
        <rgb name="sigma_s" value="0, 0, 0"/>
        <rgb name="sigma_a" value="4, 4, 2"/>
    </medium>
<shape>
```
it seems to me, that the variable-naming, as well as the value-range changed, like so:

```
<shape type="...">
    <bsdf type="dielectric">
        <float name="int_ior" value="1.504"/>
        <float name="ext_ior" value="1.0"/>
    </bsdf>

    <medium type="homogeneous" name="interior">
        <rgb name="sigma_t" value="0, 0, 0"/>
        <rgb name="albedo" value="0.015, 0.015, 0.007"/>   <-- now between [0,1]  
    </medium>
<shape>
```

Do you prefer a PR for this one?

**Comment by dvicini** [comment]
Hi

It is a known issue that optimization of media is currently not supported. The reason for that is that since the publication of the original Mitsuba 2 paper, we rewrote our medium implementation to support spectrally varying extinction coefficients.

It is on our roadmap to fix the GPU versions of these integrators. The issue you are seeing is probably a very small thing to fix (i.e. by initializing all variables properly). I can't give you a timeline yet on when you can optimize heterogeneous media (efficiently) with current implementation. If you are in need to optimize media in the way we did in our original paper, I would be happy to provide you our old code which did that (using ray marching). Please let me know what you need to be able to do what you want to do. 

We now have two medium integrators in the current version: 
- `volpath`: This is a simple volumetric path tracer, and does MIS only for surfaces, but not for anything related to the medium sampling. This is slightly more sophisticated than `volpath-simple` in Mitsuba 1, since that integrator did not do any MIS at all (not even surfaces). This integrator also does shadow connections through null interfaces and supports polarization for the surface scattering. 
- `volpathmis`: This integrator is based on the work by Miller et al. 2019, which allows to do full MIS for heterogeneous media. Most notably, this integrator efficiently handles spectrally varying extinction coefficients. This is something which Mitsuba 1 did not support. This integrator currently does not support polarization

Thanks for pointing out the issue in the doc. For these small changes it's best to just make a pull request :) 

Delio

**Comment by dnageo** [comment]
Hey @dvicini ,
thank you for responding so fast and detailed!

I would like to be able to model a deep-sea underwater scenario, i.e, a view through a glass-interface into a water column. As it is dark down there, the volume has to be illuminated with artificial light.

So first I would like to be able to parametrize my volume -- water -- in a proper manner.
In #102 you mention that 

> For a medium which only absorbs light, you need to have albedo = 0 and a non-zero albedo.

I think this will again lead me to a paremetrization of something invisible ;) Looking again at `homogeneous.cpp` I think you maybe meant albedo = 0 0 0 and  non-zero sigma_t ?

To have scattering I also altered the albedo-values and added the hg-phase function with g=0.8. The result  looks quite reasonable for a start.

In #100 I see that there is a spot light coming,  which will also be differentiable somewhen. But this is optional, as I would like to start out by trying to figure out the water properties (in terms of attenuation and scattering ) in a test tank. To do this in the spectral domain inside a homogenoeus medium would be great to begin with.

In addition, if you could give me a hint what is a good way of introspection on Ubuntu 18, I would be very grateful. I obviously already see that something is uninitialized ;) But what? 

After compiling mitsuba in debug mode I --inter alia -- tried 
- gdb
- cuda-gdb
- Nsight-Eclipse edition <-- haven't been able to compile anything here yet
- In addition, I can increase the cuda_debug level of enoki above 4:
> ek.cuda_set_log_level(4)

But still I don't have a clue yet, where that variable stems from. If you don't consider it a waste of effort -- because you reimplement everything anyways -- I would try to find it to eventually  initialize it.

**Comment by dvicini** [comment]
Hi, 

Yes, I meant to write non-zero sigmat. 

I just had a look now and pushed a fix. The uninitialized variable error was triggered by some variables in the volumetric integrator indeed being uninitialized. The GPU mode is fairly strict when it comes to this. With the latest version on master, both `volpath` and `volpathmis` should run on the GPU and match the results of the CPU versions. I haven't tested optimization yet, and that might still require a few adjustments. I can have a look next week probably

Delio

**Comment by dnageo** [comment]
Hi Delio,

thank you very much: `volpath` as well as `volpathmis` are now working in GPU-mode! I'm looking forward to any volumetric optimization possibilities within the scenarios described above.

Cheers
David

**Comment by dvicini** [comment]
Hi David, 

I finally had some time to look into it. It turned out that optimization of homogeneous volume parameters already works. I haven't tested it much, so there might be still some small issues and some limitations. One limitation is that It's currently only possible to optimize for albedo and sigma_t parameters between 0 and 1. The medium classes have an additional `density` parameters which is used to scale sigma_t to achieve extinction > 1. The reason the parameters are currently factored like this is related to spectral rendering. Either way, the `density` parameter cannot be optimized yet (currently optimization of scalar float parameters is not yet supported). I would suggest to just set density "high enough" and then initialize your volume with a fairly small sigma_t parameter.

One important thing to be aware of is that the volume optimization will diverge if you don't force the parameters to be in a  valid range (e.g. a negative extinction won't work). 

I've created a simple example script to optimize for sigma_t where I also make sure to keep sigma_t in a valid range:  
https://gist.github.com/dvicini/d0e219bc7dadbd949cfab177c9fcef17

I hope this helps you getting started. I will close this issue for now, since the basic optimization does work now

Delio
